language: ruby	
before_install:	
- sudo apt-get update -q && sudo apt-get install nodejs -yqq	
- sudo apt-get install libpq-dev -yqq	
- gem update --system	
- gem install bundler	
- gem install rails	
- rm -rf Gemfile.lock
- export CODECOV_TOKEN=5b133954-0a11-4bd5-9019-64dc164400cf	
- bundle update	 
